import { Document as DocxDocument, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import { Document as PdfDocument, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { createElement } from "react";
import { lessonContentSchema, type Lesson } from "@/lib/lesson";

export const runtime = "nodejs";
const styles=StyleSheet.create({page:{padding:40,fontSize:10,fontFamily:"Helvetica",color:"#182a22"},brand:{fontSize:22,fontFamily:"Times-Roman",marginBottom:6},meta:{color:"#ae4c2d",fontSize:9,marginBottom:16},heading:{fontSize:15,fontFamily:"Times-Roman",marginTop:14,marginBottom:6},item:{lineHeight:1.55,marginBottom:5},row:{borderBottom:"1 solid #d8d4c9",paddingVertical:7},time:{color:"#ae4c2d",fontSize:9,marginBottom:2}});

function parseLesson(value:unknown):Lesson { const candidate=value as Lesson; return {...candidate,content:lessonContentSchema.parse(candidate.content)}; }
function lessonText(lesson:Lesson){return [`Adhyaya — Official Lesson Note`,lesson.content.title,`${lesson.classGroup} · ${lesson.subject} · ${lesson.date} · ${lesson.period} · ${lesson.duration} minutes`,`Learning outcomes`,...lesson.content.learningOutcomes.map(x=>`• ${x}`),`Teaching sequence`,...lesson.content.sequence.flatMap(x=>[`${x.minutes} min · ${x.title}`,x.teacherAction,`Students: ${x.studentAction}`]),`Materials / TLM`,...lesson.content.materials.map(x=>`• ${x}`),`Assessment`,...lesson.content.assessment.map(x=>`• ${x}`),`Assignment`,lesson.content.assignment??"—"];}
function pdfTree(lesson:Lesson){const section=(title:string,items:string[])=>createElement(View,{key:title},createElement(Text,{style:styles.heading},title),...items.map((item,i)=>createElement(Text,{key:i,style:styles.item},`• ${item}`)));return createElement(PdfDocument,null,createElement(Page,{size:"A4",style:styles.page},createElement(Text,{style:styles.brand},"Adhyaya"),createElement(Text,{style:styles.meta},`OFFICIAL LESSON NOTE  ·  ${lesson.classGroup}  ·  ${lesson.subject}  ·  ${lesson.date}  ·  ${lesson.period}`),createElement(Text,{style:{fontSize:22,fontFamily:"Times-Roman"}},lesson.content.title),section("Learning outcomes",lesson.content.learningOutcomes),createElement(Text,{style:styles.heading},"Teaching sequence"),...lesson.content.sequence.map((s,i)=>createElement(View,{key:i,style:styles.row},createElement(Text,{style:styles.time},`${s.minutes} MIN · ${s.title.toUpperCase()} · ${s.method}`),createElement(Text,{style:styles.item},s.teacherAction),createElement(Text,{style:styles.item},`Students: ${s.studentAction}`))),section("Materials / TLM",lesson.content.materials),section("Assessment",lesson.content.assessment),section("Assignment",[lesson.content.assignment??"—"])))}
export async function POST(request:Request){try{const lesson=parseLesson(await request.json());const format=new URL(request.url).searchParams.get("format");if(format==="docx"){const doc=new DocxDocument({sections:[{children:lessonText(lesson).map((line,index)=>new Paragraph({heading:index===0?HeadingLevel.TITLE:index===3||index===6||index===12||index===15||index===18?HeadingLevel.HEADING_2:undefined,children:[new TextRun(line)]}))}]});const buffer=await Packer.toBuffer(doc);return new Response(new Uint8Array(buffer),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":"attachment; filename=lesson-plan.docx"}})}const buffer=await renderToBuffer(pdfTree(lesson));return new Response(new Uint8Array(buffer),{headers:{"Content-Type":"application/pdf","Content-Disposition":"attachment; filename=lesson-plan.pdf"}})}catch{return Response.json({message:"We couldn't prepare this export. Your lesson is still safe."},{status:400})}}
