"use client";
/* eslint-disable @next/next/no-location-assign-relative-destination */

import { BookOpen, Plus, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";

import type { CurriculumSetupCatalogue } from "@/lib/app-types";
import { normalizeOptionalTime } from "@/lib/onboarding";

type ClassInput = { curriculumClassId: string; section: string };
type AssignmentInput = { classIndex: number; curriculumSubjectId: string };
type PeriodInput = { label: string; startsAt: string; endsAt: string };
type TimetableInput = { weekday: number; periodIndex: number; assignmentIndex: number };

const weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

export default function OnboardingPage() {
  const [catalogue, setCatalogue] = useState<CurriculumSetupCatalogue | null>(null); const [catalogueError, setCatalogueError] = useState<string | null>(null);
  const [workspaceName, setWorkspaceName] = useState(""); const [schoolName, setSchoolName] = useState(""); const [displayName, setDisplayName] = useState("");
  const [classes, setClasses] = useState<ClassInput[]>([]); const [assignments, setAssignments] = useState<AssignmentInput[]>([]); const [periods, setPeriods] = useState<PeriodInput[]>([]); const [timetable, setTimetable] = useState<TimetableInput[]>([]);
  const [classId, setClassId] = useState(""); const [section, setSection] = useState(""); const [assignmentClassIndex, setAssignmentClassIndex] = useState(""); const [curriculumSubjectId, setCurriculumSubjectId] = useState(""); const [period, setPeriod] = useState("");
  const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { void (async () => { const response = await fetch("/api/curriculum/options", { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) setCatalogueError(body.message ?? "Could not load the verified curriculum."); else setCatalogue(body); })(); }, []);
  const selectedClassIndex = assignmentClassIndex === "" ? -1 : Number(assignmentClassIndex); const selectedClass = classes[selectedClassIndex];
  const availableSubjects = useMemo(() => selectedClass && catalogue ? catalogue.subjects.filter((subject) => subject.curriculumClassId === selectedClass.curriculumClassId) : [], [catalogue, selectedClass]);
  const className = (id: string) => catalogue?.classes.find((item) => item.id === id)?.name ?? "Selected class";
  const subjectName = (id: string) => catalogue?.subjects.find((item) => item.id === id)?.name ?? "Selected subject";
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setSaving(true); const response = await fetch("/api/onboarding", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workspaceName, schoolName: schoolName || null, displayName, defaultDurationMinutes: 45, classes, assignments, periods: periods.map((item) => ({ ...item, startsAt: normalizeOptionalTime(item.startsAt), endsAt: normalizeOptionalTime(item.endsAt) })), timetable }) }); if (response.ok) window.location.assign("/"); else { const body = await response.json().catch(() => ({})); setError(body.message ?? "Please check the setup details and try again."); setSaving(false); } };
  const addClass = () => { if (classId && section.trim() && !classes.some((item) => item.curriculumClassId === classId && item.section.toLowerCase() === section.trim().toLowerCase())) { setClasses((items) => [...items, { curriculumClassId: classId, section: section.trim() }]); setClassId(""); setSection(""); } };
  const addAssignment = () => { if (selectedClassIndex >= 0 && curriculumSubjectId && !assignments.some((item) => item.classIndex === selectedClassIndex && item.curriculumSubjectId === curriculumSubjectId)) { setAssignments((items) => [...items, { classIndex: selectedClassIndex, curriculumSubjectId }]); setCurriculumSubjectId(""); } };
  const addPeriod = () => { if (period.trim()) { setPeriods((items) => [...items, { label: period.trim(), startsAt: "", endsAt: "" }]); setPeriod(""); } };
  const removeClass = (index: number) => { setClasses((items) => items.filter((_, itemIndex) => itemIndex !== index)); setAssignments((items) => items.filter((assignment) => assignment.classIndex !== index).map((assignment) => assignment.classIndex > index ? { ...assignment, classIndex: assignment.classIndex - 1 } : assignment)); };
  return <main className="paper min-h-screen px-5 py-10 md:px-10"><form onSubmit={submit} className="mx-auto max-w-4xl"><header className="border-b border-[var(--line)] pb-8"><div className="flex items-center gap-2"><BookOpen className="size-6 text-[var(--green)]"/><span className="serif text-3xl font-bold">Adhyaya</span></div><p className="mt-10 text-sm font-semibold tracking-[.14em] text-[var(--clay)]">FIRST, YOUR REAL TEACHING CONTEXT</p><h1 className="serif mt-3 text-5xl font-bold md:text-6xl">Set up the workspace you actually teach in.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-[var(--muted)]">Choose the verified CBSE/NCERT class and subject for every teaching assignment. Your section names and timetable remain yours.</p></header>
    {catalogueError ? <p role="alert" className="mt-10 border-l-2 border-[var(--clay)] pl-4 text-[var(--clay)]">{catalogueError}</p> : !catalogue ? <p className="mt-10 text-[var(--muted)]">Loading verified curriculum choices…</p> : <div className="mt-10 grid gap-10 lg:grid-cols-2"><section className="space-y-5"><h2 className="serif text-3xl font-bold">Teacher and school</h2><Input label="Your display name" value={displayName} onChange={setDisplayName} placeholder="Name shown in your workspace" required/><Input label="Workspace name" value={workspaceName} onChange={setWorkspaceName} placeholder="For example, your school or department" required/><Input label="School name" value={schoolName} onChange={setSchoolName} placeholder="Optional"/></section>
    <section><h2 className="serif text-3xl font-bold">Classes and subjects</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Classes and subjects use verified canonical IDs, not display labels.</p><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><select aria-label="Canonical class" value={classId} onChange={(event) => setClassId(event.target.value)} className="field"><option value="">Select class</option>{catalogue.classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input value={section} onChange={(event) => setSection(event.target.value)} placeholder="Section B" className="field"/><button type="button" onClick={addClass} className="focus-ring rounded-md border border-[var(--green)] px-4 font-semibold text-[var(--green)]"><Plus className="inline size-4"/> Add</button></div><div className="mt-4 space-y-2">{classes.map((item, index) => <Row key={`${item.curriculumClassId}-${item.section}`} text={`${className(item.curriculumClassId)} · ${item.section}`} onRemove={() => removeClass(index)}/>)}</div>{classes.length > 0 && <div className="mt-6 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><select aria-label="Class for subject mapping" value={assignmentClassIndex} onChange={(event) => { setAssignmentClassIndex(event.target.value); setCurriculumSubjectId(""); }} className="field"><option value="">Select class section</option>{classes.map((item, index) => <option key={`${item.curriculumClassId}-${item.section}`} value={index}>{className(item.curriculumClassId)} · {item.section}</option>)}</select><select aria-label="Canonical subject" value={curriculumSubjectId} onChange={(event) => setCurriculumSubjectId(event.target.value)} disabled={selectedClassIndex < 0} className="field disabled:opacity-50"><option value="">Select subject</option>{availableSubjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button type="button" onClick={addAssignment} className="focus-ring rounded-md border border-[var(--green)] px-4 font-semibold text-[var(--green)]"><Plus className="inline size-4"/> Map</button></div>}<div className="mt-4 space-y-2">{assignments.map((item, index) => <Row key={`${item.classIndex}-${item.curriculumSubjectId}`} text={`${classes[item.classIndex] ? `${className(classes[item.classIndex].curriculumClassId)} · ${classes[item.classIndex].section}` : "Removed class"} — ${subjectName(item.curriculumSubjectId)}`} onRemove={() => setAssignments((items) => items.filter((_, itemIndex) => itemIndex !== index))}/>)}</div></section>
    <section><h2 className="serif text-3xl font-bold">Teaching periods</h2><div className="mt-5 flex gap-3"><input value={period} onChange={(event) => setPeriod(event.target.value)} placeholder="For example, Period 1" className="field"/><button type="button" onClick={addPeriod} className="focus-ring rounded-md border border-[var(--green)] px-4 font-semibold text-[var(--green)]"><Plus className="inline size-4"/> Add</button></div><p className="mt-3 text-sm text-[var(--muted)]">Start and end times are optional; blank values are normalized to null before saving.</p><div className="mt-4 space-y-3">{periods.map((item, index) => <div key={`${item.label}-${index}`} className="grid gap-3 sm:grid-cols-[1fr_9rem_9rem_auto]"><input value={item.label} onChange={(event) => setPeriods((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, label: event.target.value } : value))} className="field" aria-label={`Label for period ${index + 1}`}/><input type="time" value={item.startsAt} onChange={(event) => setPeriods((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, startsAt: event.target.value } : value))} className="field" aria-label={`Start time for ${item.label}`}/><input type="time" value={item.endsAt} onChange={(event) => setPeriods((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, endsAt: event.target.value } : value))} className="field" aria-label={`End time for ${item.label}`}/><button type="button" onClick={() => setPeriods((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="focus-ring rounded p-3 text-[var(--clay)]" aria-label={`Remove ${item.label}`}><Trash2 className="size-4"/></button></div>)}</div></section>
    <section><h2 className="serif text-3xl font-bold">Weekly timetable <span className="text-base font-normal text-[var(--muted)]">(optional now)</span></h2><p className="mt-2 text-[var(--muted)]">Add a teaching slot using a verified class-subject mapping.</p>{assignments.length > 0 && periods.length > 0 && <button type="button" onClick={() => setTimetable((items) => [...items, { weekday: 1, periodIndex: 0, assignmentIndex: 0 }])} className="focus-ring mt-4 font-semibold text-[var(--clay)]"><Plus className="inline size-4"/> Add a teaching slot</button>}<div className="mt-4 space-y-3">{timetable.map((item, index) => <div key={index} className="grid gap-3 border-y border-[var(--line)] py-3 md:grid-cols-[1fr_1fr_1fr_auto]"><select value={item.weekday} onChange={(event) => setTimetable((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, weekday: Number(event.target.value) } : value))} className="field">{weekdays.map((day, dayIndex) => <option key={day} value={dayIndex + 1}>{day}</option>)}</select><select value={item.periodIndex} onChange={(event) => setTimetable((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, periodIndex: Number(event.target.value) } : value))} className="field">{periods.map((entry, entryIndex) => <option key={entryIndex} value={entryIndex}>{entry.label}</option>)}</select><select value={item.assignmentIndex} onChange={(event) => setTimetable((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, assignmentIndex: Number(event.target.value) } : value))} className="field">{assignments.map((entry, entryIndex) => <option key={entryIndex} value={entryIndex}>{classes[entry.classIndex] ? `${className(classes[entry.classIndex].curriculumClassId)} · ${classes[entry.classIndex].section} — ${subjectName(entry.curriculumSubjectId)}` : "Removed mapping"}</option>)}</select><button type="button" onClick={() => setTimetable((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="focus-ring rounded p-3 text-[var(--clay)]" aria-label="Remove teaching slot"><Trash2 className="size-4"/></button></div>)}</div></section></div>}
    {error && <p role="alert" className="mt-8 text-[var(--clay)]">{error}</p>}<button disabled={saving || !catalogue || Boolean(catalogueError)} className="focus-ring mt-12 min-h-14 w-full rounded-md bg-[var(--green)] px-6 text-lg font-semibold text-white enabled:hover:bg-[#0e3726] disabled:opacity-60">{saving ? "Saving your workspace…" : "Start planning"}</button></form></main>;
}

function Input({ label, value, onChange, placeholder, required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; required?: boolean }) { return <label className="block"><span className="mb-2 block font-semibold">{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required={required} className="field"/></label>; }
function Row({ text, onRemove }: { text: string; onRemove: () => void }) { return <div className="flex items-center justify-between border-y border-[var(--line)] py-3"><span className="text-sm font-medium">{text}</span><button type="button" onClick={onRemove} className="focus-ring rounded p-2 text-[var(--clay)]" aria-label={`Remove ${text}`}><Trash2 className="size-4"/></button></div>; }
