"use client";
/* eslint-disable @next/next/no-location-assign-relative-destination */

import { BookOpen, Plus, Trash2 } from "lucide-react";
import { FormEvent, useState } from "react";

type ClassInput = { grade: string; section: string };
type PeriodInput = { label: string; startsAt: string; endsAt: string };
type TimetableInput = { weekday: number; periodIndex: number; classIndex: number; subjectIndex: number };

const weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

export default function OnboardingPage() {
  const [workspaceName, setWorkspaceName] = useState(""); const [schoolName, setSchoolName] = useState(""); const [displayName, setDisplayName] = useState("");
  const [classes, setClasses] = useState<ClassInput[]>([]); const [subjects, setSubjects] = useState<string[]>([]); const [periods, setPeriods] = useState<PeriodInput[]>([]); const [timetable, setTimetable] = useState<TimetableInput[]>([]);
  const [grade, setGrade] = useState(""); const [section, setSection] = useState(""); const [subject, setSubject] = useState(""); const [period, setPeriod] = useState("");
  const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setSaving(true); const response = await fetch("/api/onboarding", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workspaceName, schoolName: schoolName || null, displayName, defaultDurationMinutes: 45, classes, subjects, periods, timetable }) }); if (response.ok) window.location.assign("/"); else { const body = await response.json().catch(() => ({})); setError(body.message ?? "Please check the setup details and try again."); setSaving(false); } };
  const addClass = () => { if (grade.trim() && section.trim()) { setClasses((items) => [...items, { grade: grade.trim(), section: section.trim() }]); setGrade(""); setSection(""); } };
  const addSubject = () => { if (subject.trim() && !subjects.includes(subject.trim())) { setSubjects((items) => [...items, subject.trim()]); setSubject(""); } };
  const addPeriod = () => { if (period.trim()) { setPeriods((items) => [...items, { label: period.trim(), startsAt: "", endsAt: "" }]); setPeriod(""); } };
  return <main className="paper min-h-screen px-5 py-10 md:px-10"><form onSubmit={submit} className="mx-auto max-w-4xl"><header className="border-b border-[var(--line)] pb-8"><div className="flex items-center gap-2"><BookOpen className="size-6 text-[var(--green)]"/><span className="serif text-3xl font-bold">Adhyaya</span></div><p className="mt-10 text-sm font-semibold tracking-[.14em] text-[var(--clay)]">FIRST, YOUR REAL TEACHING CONTEXT</p><h1 className="serif mt-3 text-5xl font-bold md:text-6xl">Set up the workspace you actually teach in.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-[var(--muted)]">Nothing is prefilled. Add the school, classes, subjects, and periods that belong to your timetable; you can refine them later in Settings.</p></header>
    <div className="mt-10 grid gap-10 lg:grid-cols-2"><section className="space-y-5"><h2 className="serif text-3xl font-bold">Teacher and school</h2><Input label="Your display name" value={displayName} onChange={setDisplayName} placeholder="Name shown in your workspace" required/><Input label="Workspace name" value={workspaceName} onChange={setWorkspaceName} placeholder="For example, your school or department" required/><Input label="School name" value={schoolName} onChange={setSchoolName} placeholder="Optional"/></section>
    <section><h2 className="serif text-3xl font-bold">Classes and subjects</h2><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input value={grade} onChange={(e) => setGrade(e.target.value)} placeholder="Class VIII" className="field"/><input value={section} onChange={(e) => setSection(e.target.value)} placeholder="Section B" className="field"/><button type="button" onClick={addClass} className="focus-ring rounded-md border border-[var(--green)] px-4 font-semibold text-[var(--green)]"><Plus className="inline size-4"/> Add</button></div><Chips items={classes.map((item) => `${item.grade} — ${item.section}`)} remove={(index) => setClasses((items) => items.filter((_, itemIndex) => itemIndex !== index))}/><div className="mt-7 flex gap-3"><input value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="Subject name" className="field"/><button type="button" onClick={addSubject} className="focus-ring rounded-md border border-[var(--green)] px-4 font-semibold text-[var(--green)]"><Plus className="inline size-4"/> Add</button></div><Chips items={subjects} remove={(index) => setSubjects((items) => items.filter((_, itemIndex) => itemIndex !== index))}/></section>
    <section><h2 className="serif text-3xl font-bold">Teaching periods</h2><div className="mt-5 flex gap-3"><input value={period} onChange={(e) => setPeriod(e.target.value)} placeholder="For example, Period 1" className="field"/><button type="button" onClick={addPeriod} className="focus-ring rounded-md border border-[var(--green)] px-4 font-semibold text-[var(--green)]"><Plus className="inline size-4"/> Add</button></div><div className="mt-4 space-y-3">{periods.map((item, index) => <div key={`${item.label}-${index}`} className="grid grid-cols-[1fr_auto] gap-3"><input value={item.label} onChange={(e) => setPeriods((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, label: e.target.value } : value))} className="field"/><button type="button" onClick={() => setPeriods((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="focus-ring rounded p-3 text-[var(--clay)]" aria-label={`Remove ${item.label}`}><Trash2 className="size-4"/></button></div>)}</div></section>
    <section><h2 className="serif text-3xl font-bold">Weekly timetable <span className="text-base font-normal text-[var(--muted)]">(optional now)</span></h2><p className="mt-2 text-[var(--muted)]">Add one teaching slot at a time. Planner rows remain blank until a slot is assigned.</p>{classes.length > 0 && subjects.length > 0 && periods.length > 0 && <button type="button" onClick={() => setTimetable((items) => [...items, { weekday: 1, periodIndex: 0, classIndex: 0, subjectIndex: 0 }])} className="focus-ring mt-4 font-semibold text-[var(--clay)]"><Plus className="inline size-4"/> Add a teaching slot</button>}<div className="mt-4 space-y-3">{timetable.map((item, index) => <div key={index} className="grid gap-3 border-y border-[var(--line)] py-3 md:grid-cols-[1fr_1fr_1fr_1fr_auto]"><select value={item.weekday} onChange={(e) => setTimetable((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, weekday: Number(e.target.value) } : value))} className="field">{weekdays.map((day, dayIndex) => <option key={day} value={dayIndex + 1}>{day}</option>)}</select><select value={item.periodIndex} onChange={(e) => setTimetable((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, periodIndex: Number(e.target.value) } : value))} className="field">{periods.map((entry, entryIndex) => <option key={entryIndex} value={entryIndex}>{entry.label}</option>)}</select><select value={item.classIndex} onChange={(e) => setTimetable((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, classIndex: Number(e.target.value) } : value))} className="field">{classes.map((entry, entryIndex) => <option key={entryIndex} value={entryIndex}>{entry.grade}-{entry.section}</option>)}</select><select value={item.subjectIndex} onChange={(e) => setTimetable((items) => items.map((value, itemIndex) => itemIndex === index ? { ...value, subjectIndex: Number(e.target.value) } : value))} className="field">{subjects.map((entry, entryIndex) => <option key={entryIndex} value={entryIndex}>{entry}</option>)}</select><button type="button" onClick={() => setTimetable((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="focus-ring rounded p-3 text-[var(--clay)]" aria-label="Remove teaching slot"><Trash2 className="size-4"/></button></div>)}</div></section></div>
    {error && <p role="alert" className="mt-8 text-[var(--clay)]">{error}</p>}<button disabled={saving} className="focus-ring mt-12 min-h-14 w-full rounded-md bg-[var(--green)] px-6 text-lg font-semibold text-white enabled:hover:bg-[#0e3726] disabled:opacity-60">{saving ? "Saving your workspace…" : "Start planning"}</button></form></main>;
}

function Input({ label, value, onChange, placeholder, required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; required?: boolean }) { return <label className="block"><span className="mb-2 block font-semibold">{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required={required} className="field"/></label>; }
function Chips({ items, remove }: { items: string[]; remove: (index: number) => void }) { return <div className="mt-4 flex flex-wrap gap-2">{items.map((item, index) => <span key={`${item}-${index}`} className="inline-flex items-center gap-2 rounded-full border border-[var(--line)] bg-white/60 px-3 py-1 text-sm">{item}<button type="button" onClick={() => remove(index)} className="focus-ring text-[var(--clay)]" aria-label={`Remove ${item}`}><Trash2 className="size-3"/></button></span>)}</div>; }
